### ISSUE TITLE
snaptik.app

### ISSUE THREAD

**Issue by takedowndmca** [Arya-was/simple-api#14]
request tambahin discraper bg hehe
[snaptik.app](https://snaptik.app/ID)

**Comment by Arya-was** [comment]
Musicallydown, savetik, ttdown
kan ada

**Comment by takedowndmca** [comment]
webnya savetik udah ga work bg hehe :)

**Comment by Arya-was** [comment]
> webnya savetik udah ga work bg hehe :)

bisa bre harusnya, baca bissmillah aja:v,k kalo beneran ngga bisa pakai tttdown sama musically aja kayak di Api

**Comment by takedowndmca** [comment]
oke bg, thanks :)
